defaults:
    - base

name: SVP
logging: true

n_past: 10
n_future: 10
vf_skip: true  

lstm:
    hidden_dim: 256
    layers: 2

autoencoder:
    c_hid: 64
    latent_dim: 128

data:
    name: moving_mnist
    shape: [1, 64, 64]
    deterministic: true

param:
    lr: 5e-4
    batch_size: 100
    r: 0.2 # reconstruction loss factor

trainer:
    max_steps: 100_000
    check_val_every_n_epoch: 1

logger:
    project: svp-experiments